name: Build and Release Plugin

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build plugin
        run: mvn clean package

      - name: Get plugin version
        id: get_version
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "Plugin version: $VERSION"

      - name: List JAR files
        run: ls -l target/*.jar

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION }}-${{ github.run_number }}
          release_name: Release v${{ env.VERSION }}-${{ github.run_number }}
          body: |
            Описание вашего релиза
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload JAR files to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/TwinksCheker-${{ env.VERSION }}.jar
          asset_name: TwinksCheker-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive

